Update coverage workflow to run only once a month

diff --git a/riscof-plugins/rv32/check_coverage b/riscof-plugins/rv32/check_coverage
--- a/riscof-plugins/rv32/check_coverage
+++ b/riscof-plugins/rv32/check_coverage
@@ -10,8 +10,8 @@ riscof coverage --config=config.ini --cgf-file ../../coverage/dataset.cgf \
   --suite ../../riscv-test-suite/rv32i_m/I \
   --env ../../riscv-test-suite/env \
   -h ../../coverage/header_file.yaml
- -d riscof_work ] && echo "riscof_work exists ✅" || echo "riscof_work missing ❌"
-echo "📊 Extracting RISCOF Coverage Summary..."
+ -d riscof_work ] && echo "riscof_work exists" || echo "riscof_work missing"
+echo "Extracting RISCOF Coverage Summary..."
 w3m -dump riscof_work/coverage.html > coverage.txt
 
 # Print total coverpoints line
@@ -32,9 +32,9 @@ riscof coverage --config=config.ini --cgf-file ../../coverage/dataset.cgf \
   --suite ../../riscv-test-suite/rv32i_m/M \
   --env ../../riscv-test-suite/env \
   -h ../../coverage/header_file.yaml
-[ -d riscof_work ] && echo "riscof_work exists ✅" || echo "riscof_work missing ❌"
+[ -d riscof_work ] && echo "riscof_work exists" || echo "riscof_work missing"
 w3m -dump riscof_work/coverage.html > coverage.txt
-echo "📊 Extracting RISCOF Coverage Summary..."
+echo "Extracting RISCOF Coverage Summary..."
 
 # Print total coverpoints line
 grep "Total Coverpoints" coverage.txt
@@ -53,9 +53,9 @@ mv riscof_work all_riscof_works/riscof_work_M
 #   --suite ../../riscv-test-suite/rv32i_m/C \
 #   --env ../../riscv-test-suite/env \
 #   -h ../../coverage/header_file.yaml
-# [ -d riscof_work ] && echo "riscof_work exists ✅" || echo "riscof_work missing ❌"
+# [ -d riscof_work ] && echo "riscof_work exists" || echo "riscof_work missing"
 # w3m -dump riscof_work/coverage.html > coverage.txt
-# echo "📊 Extracting RISCOF Coverage Summary..."
+# echo "Extracting RISCOF Coverage Summary..."
 
 # # Print total coverpoints line
 # grep "Total Coverpoints" coverage.txt
